### ISSUE TITLE
Make repository nice

### ISSUE THREAD

**Issue by wattai** [wattai/sound-source-position-estimation#1]
## TODO

- [x] migrate legacy codes
- [ ] write README.md
- [ ] refactor codes
  - [ ] add some objects for soundsources, microphones, and environments like air.
- [ ] add some demo code or results in README.md
